os: osx
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.0
node_js:
- '8'
- '10'
- '12'
sudo: false
before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run coverage
