os: osx
osx_image: xcode11.6
xcode_sdk: iphonesimulator13.6
language: node_js
node_js:
  - "10"
  - "12"
  - "14"
sudo: false
before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run coverage
