name: Build
on:
  push:
    branches:
    - master
    - "[0-9]+_X"
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: yarn
        name: Install dependencies

      - name: Build and Test
        run: yarn run test
